authapp/urls.py
from django.urls import path
from authapp.views import SignInView, SignUpView, SignOutView, VerifyView, UserUpdateView

app_name = 'authapp'
urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('edit/<pk>/', UserUpdateView.as_view(), name='edit'),
    path('verify/', VerifyView.as_view(), name='verify'),
]

chatapp/urls.py
from django.urls import path, include
import chatapp.views as chatapp


app_name = 'shoppingapp'
urlpatterns = [
    path('', chatapp.chatpage, name='chatpage'),
]

eventapp/urls.py
from django.urls import path, include
import eventapp.views as eventapp


app_name = 'eventapp'

urlpatterns = [
    path('show_events/', eventapp.show_events, name='show_events'),
    path('archived_events/', eventapp.archived_events, name='archived_events'),
    path('create_event/', eventapp.create_event, name='create_event'),
    path('read_event/<event_pk>', eventapp.read_event, name='read_event'),
    path('read_archived_event/<event_pk>', eventapp.read_archived_event, name='read_archived_event'),
    path('edit_event/<event_pk>', eventapp.edit_event, name='edit_event'),
    path('leave_event/<event_pk>', eventapp.leave_event, name='leave_event'),
    path('join_event/<event_pk>', eventapp.join_event, name='join_event'),
    path('copy_event/<event_pk>', eventapp.copy_event, name='copy_event'),
]

family_space/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('groupsapp/', include('groupapp.urls', namespace='groupapp')),
                  path('auth_api/', include('api.apiauthapp.urls')),
                  path('', include('api.apiuserapp.urls')),
                  path('', include('api.apigroupapp.urls')),
                  path('', include('api.apichatapp.urls')),
                  path('', include('api.apitaskapp.urls')),
                  path('', include('api.apieventapp.urls')),
                  path('', include('api.apishopingapp.urls')),
                  path('docs/', include('api.apidocs.urls')),
                  path('auth/', include('authapp.urls', namespace='auth')),
                  path('groupsapp/<group_pk>/shoppingapp/', include('shoppingapp.urls', namespace='shop')),
                  path('groupsapp/<group_pk>/chatapp/', include('chatapp.urls', namespace='chatapp')),
                  path('groupsapp/<group_pk>/tasks/', include('taskapp.urls', namespace='taskapp')),
                  path('groupsapp/<group_pk>/eventsapp/', include('eventapp.urls', namespace='eventapp')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupapp/urls.py
from django.urls import path, include
import groupapp.views as groupapp


app_name = 'groupapp'
urlpatterns = [

    path('<int:group_pk>/participants/', groupapp.view_one_group, name='view_one_group'), #participants
    path('<int:group_pk>/participants/invite/', groupapp.invite_user, name='invite'),
    path('<int:group_pk>/participants/invite/<friend_pk>/', groupapp.addtogroup, name='addtogroup'),
    path('<int:group_pk>/participants/<friend_pk>/', groupapp.removefromgroup, name='removefromgroup'),
    path('<int:group_pk>/participants/roleedit/<participant_pk>/', groupapp.roleedit, name='roleedit'),
    # path('<user_pk>', groupapp.view_user_groups, name='view_user_groups'),
]

taskapp/urls.py
from django.urls import path
import taskapp.views as taskapp


app_name = 'taskapp'
urlpatterns = [
    path('', taskapp.view_tasks_list, name='taskslist'),
    path('newtask/', taskapp.newtaskpage, name='newtask'),
    path('taskedit/<task_pk>/', taskapp.taskedit, name='taskedit'),
    path('taskremove/<task_pk>/', taskapp.taskremove, name='taskremove'),
    path('checkbox/<task_pk>/', taskapp.checkbox_tasks_list, name='checkbox'),
]

userapp/urls.py
from django.urls import path, include
import userapp.views as userapp
import groupapp.views as groupapp


app_name = 'userapps'
urlpatterns = [

    path('usercontacts/', userapp.view_user_contacts, name='usercontacts'),
    path('addcontact/<friend_pk>', userapp.addcontact, name='addcontact'),
    path('removecontact/<friend_pk>', userapp.removecontact, name='removecontact'),
    path('adduser/<group_pk>', userapp.adduser, name='adduser'),
    path('removeuser/<group_pk>', userapp.removeuser, name='removeuser'),
    path('', groupapp.view_user_groups, name='usergroups'),
    path('creategroup/', userapp.creategroup_page, name='creategroups'),
    path('editgroup/<group_pk>', userapp.editgroup, name='editgroup'),
    path('removegroup/<group_pk>', userapp.removegroup, name='removegroup'),
    path('usersearch/', userapp.usersearch, name='usersearch'),
    path('groupsearch/', userapp.groupsearch, name='groupsearch'),
]

chatapp/models.py
from django.db import models
from authapp.models import User
from groupapp.models import Group


# Create your models here.
class Chat(models.Model):
    '''
    Чат пользователей
    '''
    group = models.ForeignKey(Group,
                              verbose_name='Группа',
                              on_delete=models.CASCADE,
                              related_name='chat')
    user = models.ForeignKey(User,
                             verbose_name='Пользователь написавший сообщение',
                             on_delete='CASCADE')
    date_modify = models.DateTimeField(verbose_name='Дата и время изменения записи',
                                       auto_now=True)
    date_create = models.DateTimeField(verbose_name='Дата и время создания записи',
                                       auto_now_add=True)
    text = models.CharField(max_length=500,
                            verbose_name='Текст сообщения')

chatapp/forms.py
from django import forms
from chatapp.models import Chat

class chatform(forms.ModelForm):
    class Meta:
            model = Chat
            fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(chatform, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = "Напишите сообщение"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'logo-input'
            self.fields[field].label = ""

chatapp/views.py
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from authapp.models import User
from chatapp.forms import chatform
from groupapp.models import GroupUser, Group
from chatapp.models import Chat

# Create your views here.

def chatpage(request, group_pk):

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk)
    if not friendlyuser:
        return HttpResponseForbidden()

    form = chatform(request.POST)

    messages = Chat.objects.filter(group=group_pk)

    if request.method == 'POST':
        if form.is_valid():
            response = form.save(commit=False)
            group = get_object_or_404(Group, pk=group_pk)
            user = get_object_or_404(User, pk=request.user.pk)
            response.group = group
            response.user = user
            response.save()
            return HttpResponseRedirect(reverse('chatapp:chatpage', args=[group_pk]))
    else:
        form = chatform()

    content = {
        'messages': messages,
        'chatform': form,
        'group_pk': group_pk
    }

    return render(request, 'chatapp/chat.html', content)

chatapp/templates/chatapp/chat.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-10 p-r-10 p-t-58" action="{% url 'chatapp:chatpage' group_pk=group_pk %}" method="post">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'userapp:usergroups' %}" class="txt5">Назад</a></button>
                        <p class="txt3 creategroup-chat">Чат:</p>
                        <a href="#" class="txt3" id="drop-menu">Меню</a>
                    </div>
                    <div class="hide-menu chat-menu">
                        <ul>
                            <li><a href="{% url 'groupapp:view_one_group' group_pk=group_pk %}" class="txt3">Участники</a></li>
                            <li><a href="{% url 'shop:shoppinglist' group_pk=group_pk %}" class="txt3">Покупки</a></li>
                            <li><a href="{% url 'taskapp:taskslist' group_pk=group_pk %}" class="txt3">Задачи</a></li>
                            <li><a href="{% url 'eventapp:show_events' group_pk=group_pk %}" class="txt3">События</a></li>
                            <li><a href="{% url 'userapp:editgroup' group_pk=group_pk %}" class="txt3">Редактировать группу</a></li>
                            <li><a href="{% url 'userapp:removegroup' group_pk=group_pk %}" class="txt3">Удалить группу</a></li>
                        </ul>
                    </div>
                    <div class="messages-box">
                        {% for item in messages %}
                            {% if item.user == user %}
                                <div class="chat-messages-logged">
                                    <p class="message-text">{{ item.text }}</p>
                                    <p class="author-date-logged">{{ item.user }} {{ item.date_create }}</p>
                                </div>
                            {% else %}
                                <div class="chat-messages">
                                    <p class="message-text">{{ item.text }}</p>
                                    <p class="author-date">{{ item.user }} {{ item.date_create }}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% csrf_token %}
                    {{ chatform.as_p }}
                    <input class="message-send" type="submit" value="Отправить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}