authapp/urls.py
from django.urls import path
from authapp.views import SignInView, SignUpView, SignOutView, VerifyView, UserUpdateView

app_name = 'authapp'
urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('edit/<pk>/', UserUpdateView.as_view(), name='edit'),
    path('verify/', VerifyView.as_view(), name='verify'),
]

chatapp/urls.py
from django.urls import path, include
import chatapp.views as chatapp


app_name = 'shoppingapp'
urlpatterns = [
    path('', chatapp.chatpage, name='chatpage'),
]

eventapp/urls.py
from django.urls import path, include
import eventapp.views as eventapp


app_name = 'eventapp'

urlpatterns = [
    path('show_events/', eventapp.show_events, name='show_events'),
    path('archived_events/', eventapp.archived_events, name='archived_events'),
    path('create_event/', eventapp.create_event, name='create_event'),
    path('read_event/<event_pk>', eventapp.read_event, name='read_event'),
    path('read_archived_event/<event_pk>', eventapp.read_archived_event, name='read_archived_event'),
    path('edit_event/<event_pk>', eventapp.edit_event, name='edit_event'),
    path('leave_event/<event_pk>', eventapp.leave_event, name='leave_event'),
    path('join_event/<event_pk>', eventapp.join_event, name='join_event'),
    path('copy_event/<event_pk>', eventapp.copy_event, name='copy_event'),
]

family_space/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('groupsapp/', include('groupapp.urls', namespace='groupapp')),
                  path('auth_api/', include('api.apiauthapp.urls')),
                  path('', include('api.apiuserapp.urls')),
                  path('', include('api.apigroupapp.urls')),
                  path('', include('api.apichatapp.urls')),
                  path('', include('api.apitaskapp.urls')),
                  path('', include('api.apieventapp.urls')),
                  path('', include('api.apishopingapp.urls')),
                  path('docs/', include('api.apidocs.urls')),
                  path('auth/', include('authapp.urls', namespace='auth')),
                  path('groupsapp/<group_pk>/shoppingapp/', include('shoppingapp.urls', namespace='shop')),
                  path('groupsapp/<group_pk>/chatapp/', include('chatapp.urls', namespace='chatapp')),
                  path('groupsapp/<group_pk>/tasks/', include('taskapp.urls', namespace='taskapp')),
                  path('groupsapp/<group_pk>/eventsapp/', include('eventapp.urls', namespace='eventapp')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventapp/forms.py
from django import forms
from .models import Event, Hour, Minute, Day, Month, Year


class EventForm(forms.Form):
    title = forms.CharField(label='Краткое описание события', max_length=32)
    description = forms.CharField(label='Описание события', widget=forms.Textarea)
    location = forms.CharField(label='Место', max_length=32)
    hour = forms.ModelChoiceField(queryset=Hour.objects.all())
    minute = forms.ModelChoiceField(queryset=Minute.objects.all())
    day = forms.ModelChoiceField(queryset=Day.objects.all())
    month = forms.ModelChoiceField(queryset=Month.objects.all())
    year = forms.ModelChoiceField(queryset=Year.objects.all())

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "Событие"
        self.fields['description'].widget.attrs['placeholder'] = "Описание"
        self.fields['location'].widget.attrs['placeholder'] = "Место действия"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'
            self.fields[field].label = ""

        self.fields['hour'].widget.attrs['class'] = 'form-control'
        self.fields['minute'].widget.attrs['class'] = 'form-control'
        self.fields['day'].widget.attrs['class'] = 'form-control'
        self.fields['month'].widget.attrs['class'] = 'form-control'
        self.fields['year'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['style'] = "height:120px"

eventapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from .forms import EventForm
from django.urls import reverse
from groupapp.models import Group
from datetime import datetime
from .models import Event, EventUser, Hour, Minute, Day, Month, Year
import pytz

# Create your views here.

def get_event_form_data(form):
    title = form.cleaned_data['title']
    description = form.cleaned_data['description']
    location = form.cleaned_data['location']
    year = form.cleaned_data['year'].name
    month = form.cleaned_data['month'].name
    day = form.cleaned_data['day'].name
    hour = form.cleaned_data['hour'].name
    minute = form.cleaned_data['minute'].name
    data_dict = {'title': title, 'description': description, 'location': location, 'year': year, 'month': month, 'day': day, 'hour': hour, 'minute': minute}
    return data_dict

def set_date_time(data_dict):
    date_time = datetime(data_dict['year'], data_dict['month'], data_dict['day'], data_dict['hour'], data_dict['minute'], tzinfo=pytz.UTC)
    return date_time

def show_events(request, group_pk):
    my_group = get_object_or_404(Group, pk=group_pk)
    all_events = my_group.events.all()
    current_moment = datetime.now()
    curr_data = datetime(current_moment.year, current_moment.month, current_moment.day, current_moment.hour, current_moment.minute, tzinfo=pytz.UTC)

    for item in all_events:
        if item.date < curr_data:
            item.status = 'INA'
            item.save()
            item_users = item.eventusers.all()
            for member in item_users:
                member.role = 'PRT'
                member.save()
    events = my_group.events.filter(status='ACT').order_by('date')

    events_day = []
    if len(events) >= 1:
        events_day.append(events[0])

    box_one = 0
    while box_one < len(events):

        for i in events:
            box_one = box_one + 1
            box_two = 0
            for k in events_day:
                if i.date.day == k.date.day and i.date.month == k.date.month and i.date.year == k.date.year:
                    box_two = box_two + 1
            if box_two < 1:
                events_day.append(i)

    content = {
        'events': events,
        'group_pk': group_pk,
        'events_day': events_day
    }
    return render(request, 'eventapp/show_events.html', content)

def archived_events(request, group_pk):
    my_group = get_object_or_404(Group, pk=group_pk)
    events = my_group.events.filter(status='INA')
    content = {
        'events': events,
        'group_pk': group_pk,
    }
    return render(request, 'eventapp/archived_events.html', content)

def create_event(request, group_pk):
    message = ''
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event_info = get_event_form_data(form)
            try:
                my_dt = set_date_time(event_info)
                group = get_object_or_404(Group, pk=group_pk)
                new_event = Event.objects.create(title=event_info['title'], description=event_info['description'], location=event_info['location'], group=group, date=my_dt)
                new_event.add_participant(request.user, 'INT')
                print('Новое событие создано')
                return HttpResponseRedirect(reverse('eventapp:show_events', kwargs={'group_pk': group_pk}))
                message = 'Новое событие создано'
            except ValueError:
                print('Новое событие не создано')
                message = 'Вы ввели неправильную дату, исправьте, пожалуйста!'
        else:
            print("Форма не валидна")

    else:
        current_moment = datetime.now()
        d_minutes = (current_moment.minute//15+1)*15-current_moment.minute
        delta = datetime(2019, 4, 25, 0, d_minutes, 00) - datetime(2019, 4, 25, 0, 00, 00)
        default_moment = current_moment + delta
        initial_moment = {'hour': Hour.objects.get(name=default_moment.hour).pk,
                          'minute': Minute.objects.get(name=default_moment.minute).pk,
                          'day': Day.objects.get(name=default_moment.day).pk,
                          'month': Month.objects.get(name=default_moment.month).pk,
                          'year': Year.objects.get(name=default_moment.year).pk}
        form = EventForm(initial=initial_moment)
        message = ''
        print('message: ', message)

    content = {
        'event_form': form,
        'group_pk': group_pk,
        'message': message,
    }
    return render(request, 'eventapp/create_event.html', content)

def read_event(request, event_pk, group_pk):
    my_event = get_object_or_404(Event, pk=event_pk)
    eventusers = my_event.eventusers.all()

    members = map(lambda item: item.user, eventusers)
    is_participator = (request.user in members)

    if is_participator:
        my_user = get_object_or_404(EventUser, user=request.user, event=my_event)
        is_initiator = (my_user.role == 'INT')
    else:
        is_initiator = False

    content = {
        'group_pk': group_pk,
        'event_pk': event_pk,
        'event': my_event,
        'eventusers': eventusers,
        'is_participator': is_participator,
        'is_initiator': is_initiator,
    }
    return render(request, 'eventapp/read_event.html', content)

def read_archived_event(request, event_pk, group_pk):
    my_event = get_object_or_404(Event, pk=event_pk)
    eventusers = my_event.eventusers.all()

    content = {
        'group_pk': group_pk,
        'event': my_event,
        'eventusers': eventusers,
    }
    return render(request, 'eventapp/read_archived_event.html', content)

def leave_event(request, event_pk, group_pk):
    my_event = get_object_or_404(Event, pk=event_pk)
    my_user = get_object_or_404(EventUser, user=request.user, event=my_event)
    my_user.delete()
    eventusers = my_event.eventusers.all()
    is_participator = False

    content = {
        'group_pk': group_pk,
        'event': my_event,
        'eventusers': eventusers,
        'is_participator': is_participator,
    }
    return render(request, 'eventapp/read_event.html', content)

def join_event(request, event_pk, group_pk):
    my_event = get_object_or_404(Event, pk=event_pk)
    my_event.add_participant(request.user, 'PRT')
    eventusers = my_event.eventusers.all()
    is_participator = True

    content = {
        'group_pk': group_pk,
        'event': my_event,
        'eventusers': eventusers,
        'is_participator': is_participator,
    }
    return render(request, 'eventapp/read_event.html', content)

def edit_event(request, event_pk, group_pk):
    print('Начинаем редактирование события')
    message = ''
    my_event = get_object_or_404(Event, pk=event_pk)
    # group_pk = my_event.group.pk
    if request.method == 'POST':
        form = EventForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            location = form.cleaned_data['location']
            year = form.cleaned_data['year'].name
            month = form.cleaned_data['month'].name
            day = form.cleaned_data['day'].name
            hour = form.cleaned_data['hour'].name
            minute = form.cleaned_data['minute'].name
            try:
                my_dt = datetime(int(year), int(month), int(day), int(hour), int(minute), tzinfo=pytz.UTC)
                my_event.title = title
                my_event.description = description
                my_event.location = location
                my_event.date = my_dt
                my_event.save()
                return HttpResponseRedirect(reverse('eventapp:read_event', kwargs={'group_pk': group_pk, 'event_pk': event_pk}))
            except ValueError:
                message = 'Вы ввели неправильную дату, исправьте, пожалуйста!'

    else:
        event_moment = my_event.date
        initial_data = {'title': my_event.title,
                        'description': my_event.description,
                        'location': my_event.location,
                        'hour': Hour.objects.get(name=str(event_moment.hour)).pk,
                        'minute': Minute.objects.get(name=str(event_moment.minute)).pk,
                        'day': Day.objects.get(name=str(event_moment.day)).pk,
                        'month': Month.objects.get(name=str(event_moment.month)).pk,
                        'year': Year.objects.get(name=str(event_moment.year)).pk}
        form = EventForm(initial=initial_data)

    content = {
        'event_form': form,
        'event_pk': event_pk,
        'group_pk': group_pk,
        'message': message,
    }
    return render(request, 'eventapp/edit_event.html', content)

def copy_event(request, event_pk, group_pk):
    print('Создается новое события на основе старого')
    my_event = get_object_or_404(Event, pk=event_pk)
    group_pk = my_event.group.pk
    if request.method == 'POST':
        form = EventForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            location = form.cleaned_data['location']
            year = form.cleaned_data['year'].name
            month = form.cleaned_data['month'].name
            day = form.cleaned_data['day'].name
            hour = form.cleaned_data['hour'].name
            minute = form.cleaned_data['minute'].name
            try:
                my_dt = datetime(int(year), int(month), int(day), int(hour), int(minute), tzinfo=pytz.UTC)
                group = get_object_or_404(Group, pk=group_pk)
                new_event = Event.objects.create(title=title, description=description, location=location, group=group, date=my_dt)
                new_event.add_participant(request.user, 'INT')
                return HttpResponseRedirect(reverse('eventapp:show_events', kwargs={'group_pk': group_pk}))
            except ValueError:

eventapp/templates/eventapp/archived_events.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form class="login100-form validate-form p-l-30 p-r-30 p-t-58">

                <span class="login100-form-title">FamilySpace</span>
                <div class="btn mainpg btn-backbutton m-b-16">
                    <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'eventapp:show_events' group_pk=group_pk %}" class="txt5">Назад</a></button>
                    <p class="txt3 creategroup-p">Архив событий:</p>
                </div>


                {% for item in events %}
                    <div class="container-login100-form-btn  m-b-16">
                        <button class="login100-form-btn arch-event-btn">
                            <a href="{% url 'eventapp:read_archived_event' event_pk=item.pk group_pk=group_pk %}" class="txt7">{{ item.title }}<br> {{ item.date|date:'d-m-Y'}}</a>
                        </button>
                    </div>
                {% endfor %}

            </form>
        </div>
    </div>

</div>

{% endblock %}

eventapp/templates/eventapp/copy_event.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58" action="{% url 'eventapp:copy_event' event_pk=event_pk group_pk=group_pk %}" method="post">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg m-b-16">
                        <button class="login100-form-btn creategroup-btn" type="button"><a href="{% url 'eventapp:read_archived_event' event_pk=event_pk group_pk=group_pk %}" class="txt4">Назад</a></button>
                        <p class="txt3 creategroup-p">Дублирование события:</p>
                        <input class="login100-form-btn creategroup-btn" type="submit" value="OK">
                    </div>
                    {% include 'eventapp/inc/inc_event_form.html' %}
                </form>
            </div>
            <div>{{ message }}</div>
        </div>
    </div>
{% endblock %}

eventapp/templates/eventapp/create_event.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58" action="{% url 'eventapp:create_event' group_pk=group_pk %}" method="post">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg m-b-16">
                        <button class="login100-form-btn creategroup-btn" type="button"><a href="{% url 'eventapp:show_events' group_pk=group_pk %}" class="txt4">Назад</a></button>
                        <p class="txt3 creategroup-p">Создание события:</p>
                        <input class="login100-form-btn creategroup-btn" type="submit" value="OK">
                    </div>
                    {% include 'eventapp/inc/inc_event_form.html' %}
                </form>
            </div>
            <div>{{ message }}</div>
        </div>
    </div>
{% endblock %}

eventapp/templates/eventapp/edit_event.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58" action="{% url 'eventapp:edit_event' event_pk=event_pk group_pk=group_pk %}" method="post">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg m-b-16">
                        <button class="login100-form-btn creategroup-btn" type="button"><a href="{% url 'eventapp:read_event' event_pk=event_pk group_pk=group_pk %}" class="txt4">Назад</a></button>
                        <p class="txt3 creategroup-p">Редактировать события:</p>
                        <input class="login100-form-btn creategroup-btn" type="submit" value="OK">
                    </div>
                    {% include 'eventapp/inc/inc_event_form.html' %}
                </form>
            </div>
            <div>{{ message }}</div>
        </div>
    </div>
{% endblock %}

eventapp/templates/eventapp/read_archived_event.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-30 p-r-30 p-t-58">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <button class="login100-form-btn backbutton-search" type="button">
                            <a href="{% url 'eventapp:archived_events' group_pk=group_pk %}" class="txt5">Назад</a>
                        </button>
                        <p class="txt3 creategroup-p">Архивное событие:</p>
                        <button class="login100-form-btn backbutton-add-participant" type="button">
                            <a href="{% url 'eventapp:copy_event' event_pk=event.pk group_pk=group_pk %}" class="txt5">Копия</a>
                        </button>
                    </div>
                    <p class="txt3">Дата: {{ event.date.date|date:"d.m.Y" }}</p>
                    <p class="txt3">Время: {{ event.date.time }}</p>
                    <p class="txt3">Название: {{ event.title }}</p>
                    <p class="txt3">Описание: {{ event.description }}</p>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <p class="txt3">Участники:</p>
                    </div>
                    {% for item in eventusers %}
                        <div class="container-login100-form m-b-16">
                            <button class="login100-form-btn">
                                <a href="" class="txt3">
                                    {% if item.user  == request.user %}
                                            Вы
                                    {% else %}
                                        {{ item.user.username }}
                                    {% endif %}
                                </a>
                            </button>
                        </div>
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

eventapp/templates/eventapp/read_event.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-30 p-r-30 p-t-58">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'eventapp:show_events' group_pk=group_pk %}" class="txt5">Назад</a></button>
                        <p class="txt3 creategroup-p">Детали события:</p>
                        <button class="login100-form-btn backbutton-add-participant" type="button">
                            {% if is_initiator %}
                                <a href="{% url 'eventapp:edit_event' event_pk=event.pk group_pk=group_pk %}" class="txt5">Изменить</a>
                            {% elif is_participator %}
                                <a href="{% url 'eventapp:leave_event' event_pk=event.pk group_pk=group_pk %}" class="txt5">Уйти</a>
                            {% else %}
                                <a href="{% url 'eventapp:join_event' event_pk=event.pk group_pk=group_pk %}" class="txt5">Участвовать</a>
                            {% endif %}
                        </button>
                    </div>
                    <div class="container-login100-form m-b-16">
                        <p class="txt3">Дата: {{ event.date.date|date:"d.m.Y" }}</p>
                        <p class="txt3">Время: {{ event.date.time }}</p>
                        <p class="txt3">Название: {{ event.title }}</p>
                        <p class="txt3">Описание: {{ event.description }}</p>
                    </div>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <p class="txt3">Участники:</p>
                    </div>
                    {% for item in eventusers %}
                        <div class="container-login100-form-btn  m-b-16">
                            <button class="login100-form-btn">
                                <a href="" class="txt3">
                                    {% if item.user  == request.user %}
                                            Вы
                                    {% else %}
                                        {{ item.user.username }}
                                    {% endif %}
                                    {% if item.role == 'INT' %}
                                        *
                                    {% endif %}
                                </a>
                            </button>
                        </div>
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

eventapp/templates/eventapp/show_events.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form class="login100-form validate-form p-l-30 p-r-30 p-t-58">

                <span class="login100-form-title">FamilySpace</span>
                <div class="btn mainpg btn-backbutton-contacts">
                    <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'chatapp:chatpage' group_pk=group_pk %}" class="txt5">Назад</a></button>
                    <p class="txt3 creategroup-p">События группы:</p>
                    <button class="login100-form-btn backbutton-add-participant" type="button"><a href="{% url 'eventapp:create_event' group_pk=group_pk %}" class="txt5">Добавить</a></button>
                </div>

                <div class="container-login100-form m-b-0">
                    <button class="login100-form-btn">
                        <a href="{% url 'eventapp:archived_events' group_pk=group_pk %}" class="txt3">- - - Перейти в архив - - -</a>
                    </button>
                </div>

                {% for item in events_day %}
                    <div class="tasks-checkbox-div txt3">
                        {{ item.date.day }} {{ item.date|date:"F"}}
                    </div>
                    {% for ev in events %}
                        {% if ev.date.day == item.date.day and ev.date.month == item.date.month and ev.date.year == item.date.year %}
                            <div class="container-login100-form-btn  m-b-16">

                                <div class="tasks-div">
                                    <div class="tasks-checkbox-div txt3">
                                        {{ ev.date.time }}
                                    </div>
                                    <div class="task-title-div">
                                        <a class="txt7" href="{% url 'eventapp:read_event' event_pk=ev.pk group_pk=group_pk %}">
                                            <span class="sr-nm">{{ ev.title }}</span>
                                            <span class="add">Подробно</span>
                                        </a>
                                    </div>
                                </div>
                                <div class="search-group-drop-info" id="hide-info">
                                    <div class="task-description-div">Описание:
                                        <p class="task-description-p">{{ ev.description }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}

                {% endfor %}

            </form>
        </div>
    </div>
</div>
{% endblock %}