authapp/urls.py
from django.urls import path
from authapp.views import SignInView, SignUpView, SignOutView, VerifyView, UserUpdateView

app_name = 'authapp'
urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('edit/<pk>/', UserUpdateView.as_view(), name='edit'),
    path('verify/', VerifyView.as_view(), name='verify'),
]

chatapp/urls.py
from django.urls import path, include
import chatapp.views as chatapp


app_name = 'shoppingapp'
urlpatterns = [
    path('', chatapp.chatpage, name='chatpage'),
]

family_space/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('groupsapp/', include('groupapp.urls', namespace='groupapp')),
                  path('auth_api/', include('api.apiauthapp.urls')),
                  path('', include('api.apiuserapp.urls')),
                  path('', include('api.apigroupapp.urls')),
                  path('', include('api.apichatapp.urls')),
                  path('', include('api.apitaskapp.urls')),
                  path('', include('api.apieventapp.urls')),
                  path('', include('api.apishopingapp.urls')),
                  path('docs/', include('api.apidocs.urls')),
                  path('auth/', include('authapp.urls', namespace='auth')),
                  path('groupsapp/<group_pk>/shoppingapp/', include('shoppingapp.urls', namespace='shop')),
                  path('groupsapp/<group_pk>/chatapp/', include('chatapp.urls', namespace='chatapp')),
                  path('groupsapp/<group_pk>/tasks/', include('taskapp.urls', namespace='taskapp')),
                  path('groupsapp/<group_pk>/eventsapp/', include('eventapp.urls', namespace='eventapp')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingapp/urls.py
from django.urls import path
import shoppingapp.views as shoppingapp


app_name = 'shoppingapp'
urlpatterns = [
    path('', shoppingapp.view_group_purchases, name='shoppinglist'),
    path('purchasecreation/', shoppingapp.purchasecreation_page, name='purchasecreation'),
    path('purchasedetails/<item_pk>/', shoppingapp.purchase_edit, name='purchasedetails'),
    path('purchasedelete/<item_pk>/', shoppingapp.removeitem, name='purchaseremove'),
    path('checkbox/<item_pk>/', shoppingapp.checkbox_shop_list, name='checkbox'),
]

shoppingapp/models.py
from django.db import models
from authapp.models import User
from groupapp.models import Group

# Create your models here.

class ShopingItem(models.Model):
    title = models.CharField(verbose_name='Название товара',
                             max_length=255)
    group = models.ForeignKey(Group,
                              verbose_name='Группа',
                              on_delete=models.CASCADE,
                              related_name='shopingitems')
    user = models.ManyToManyField(User, verbose_name='Пользователи в закупке')
    done = models.BooleanField(default=False,
                               verbose_name='Покупка совершена')
    price = models.DecimalField(verbose_name='Цена покупки',
                                default=0,
                                max_digits=9,
                                decimal_places=2)
    comment = models.CharField(max_length=255,
                               verbose_name='Коментарий к покупке',
                               blank=True)

    def __str__(self):
        return self.title

shoppingapp/forms.py
from django import forms
from shoppingapp.models import ShopingItem

class PurchaseCreationForm(forms.ModelForm):
    class Meta:
            model = ShopingItem
            fields = ('title', 'user', 'price', 'comment')

    def __init__(self, *args, **kwargs):
        super(PurchaseCreationForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "Что купить"
        self.fields['comment'].widget.attrs['placeholder'] = "Комментарий"
        self.fields['price'].widget.attrs['placeholder'] = "Цена"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'
            self.fields[field].label = ""


class PurchaseEditForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 40}))

    class Meta:
            model = ShopingItem
            fields = ('title', 'group', 'user', 'price', 'done', 'comment')

    def __init__(self, *args, **kwargs):
        super(PurchaseEditForm, self).__init__(*args, **kwargs)
        self.fields['comment'].widget.attrs['placeholder'] = "Комментарий"
        self.fields['price'].widget.attrs['placeholder'] = "Цена"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'
            self.fields[field].label = ""

taskapp/forms.py
from django import forms
from taskapp.models import Task

class NewTaskForm(forms.ModelForm):
    class Meta:
            model = Task
            fields = ('title', 'user', 'description')

    def __init__(self, *args, **kwargs):
        super(NewTaskForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "Что сделать?"
        self.fields['description'].widget.attrs['placeholder'] = "Комментарий"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'
            self.fields[field].label = ""


class TaskEditForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 40}))

    class Meta:
            model = Task
            fields = ('title', 'user', 'description', 'done')

    def __init__(self, *args, **kwargs):
        super(TaskEditForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "Что сделать?"
        self.fields['description'].widget.attrs['placeholder'] = "Комментарий"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'
            self.fields[field].label = ""

shoppingapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponseForbidden, JsonResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from authapp.models import User
from groupapp.models import Group, GroupUser
from shoppingapp.forms import PurchaseCreationForm, PurchaseEditForm
from shoppingapp.models import ShopingItem

@login_required
def view_group_purchases(request, group_pk):
    '''
    Просмотр списка покупок группы по pk группы
    '''

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk)
    if not friendlyuser:
        return HttpResponseForbidden()

    donelist = ShopingItem.objects.filter(group=group_pk, done=True)
    tobuylist = ShopingItem.objects.filter(group=group_pk, done=False)

    content = {
        'done': donelist,
        'todo': tobuylist,
        'group_pk': group_pk
    }

    return render(request, 'shoppingapp/shoppinglist.html', content)

@login_required
def checkbox_shop_list(request, item_pk, group_pk):
    '''
    Функция меняет статут выполнено/невыполнено через чекбокс без захода на страницу редактирования
    '''

    if request.is_ajax():
        shop_item = ShopingItem.objects.get(pk=item_pk)
        if shop_item.done == False:
            shop_item.done = True
            shop_item.save()
        else:
            shop_item.done = False
            shop_item.save()

        donelist = ShopingItem.objects.filter(group=group_pk, done=True)
        tobuylist = ShopingItem.objects.filter(group=group_pk, done=False)

        content = {
            'done': donelist,
            'todo': tobuylist,
            'group_pk': group_pk
        }

        result = render_to_string('shoppingapp/includes/inc_shop_ajax.html', content)
        return JsonResponse({'result': result})
    else:
        return Http404

@login_required
def purchasecreation_page(request, group_pk):
    '''
    Добавление покупки в группу
    '''

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk)
    if not friendlyuser:
        return HttpResponseForbidden()

    form = PurchaseCreationForm(request.POST)

    if request.method == 'POST':
        if form.is_valid():
            response = form.save(commit=False)
            group = get_object_or_404(Group, pk=group_pk)
            response.group = group
            response.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse('shop:shoppinglist', args = [group_pk]))
    else:
        formuser = User.objects.filter(pk__in=GroupUser.objects.filter(group=group_pk).values_list('user'))
        form = PurchaseCreationForm()
        form.fields['user'].queryset = formuser

    content = {
        'purchase_form': form,
        'group_pk': group_pk
    }

    return render(request, 'shoppingapp/purchasecreation.html', content)

@transaction.atomic
def purchase_edit(request, group_pk, item_pk):
    '''
    Просмотр/изменение покупки группы
    '''

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk)
    if not friendlyuser:
        return HttpResponseForbidden()

    purchase = get_object_or_404(ShopingItem, pk=item_pk)
    form = PurchaseEditForm(request.POST, instance=purchase)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('shop:shoppinglist', args=[group_pk]))
    else:
        form = PurchaseEditForm(instance=purchase)
        formuser = User.objects.filter(pk__in=GroupUser.objects.filter(group=group_pk).values_list('user'))
        form.fields['user'].queryset = formuser

    content = {
        'edit_form': form,
        'group_pk': group_pk,
        'item_pk': item_pk,
    }

    return render(request, 'shoppingapp/purchasedetails.html', content)

@login_required
def removeitem(request, item_pk, group_pk):
    '''
    Удаление покупки
    '''

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk)
    if not friendlyuser:
        return HttpResponseForbidden()

    item = get_object_or_404(ShopingItem, pk=item_pk)
    print(item)
    item.delete()
    return HttpResponseRedirect(reverse('shop:shoppinglist', args=[group_pk]))

shoppingapp/templates/shoppingapp/purchasecreation.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58" action="{% url 'shop:purchasecreation' group_pk=group_pk %}" method="post" enctype="multipart/form-data">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg">
                        <button class="login100-form-btn creategroup-btn" type="button"><a href="{% url 'shop:shoppinglist' group_pk=group_pk %}" class="txt4">Назад</a></button>
                        <p class="txt3 creategroup-p">Новая покупка:</p>
                        <input class="login100-form-btn creategroup-btn" type="submit" value="OK">
                    </div>
                    {% csrf_token %}
                    {% for item in purchase_form %}
                        {% if 'comment' in item.as_widget %}
                            <div class="wrap-input100 validate-input m-b-16 m-t-26">
                                <textarea name="comment" cols="40" rows="10" placeholder="Комментарий" class="input100" id="id_description"></textarea>
                            </div>
                        {% else %}
                            <div class="wrap-input100 validate-input m-b-16 m-t-26">
                                {{ item }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

shoppingapp/templates/shoppingapp/purchasedetails.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58" action="{% url 'shop:purchasedetails' item_pk=item_pk group_pk=group_pk %}" method="post" enctype="multipart/form-data">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg">
                        <button class="login100-form-btn creategroup-btn" type="button"><a href="{% url 'shop:shoppinglist' group_pk=group_pk %}" class="txt4">Назад</a></button>
                        <p class="txt3 creategroup-p">Редактирование:</p>
                        <input class="login100-form-btn creategroup-btn" type="submit" value="OK">
                    </div>
                    {% csrf_token %}
                    {% for item in edit_form %}
                        {% if 'done' in item.as_widget %}
                            <p class="txt3 publickcheckbox">Покупка совершена:</p>{{ item }}
                        {% elif 'comment' in item.as_widget %}
                            <div class="wrap-input100 validate-input m-b-16 m-t-26">
                                {{ item }}
                            </div>
                        {% else %}
                            <div class="wrap-input100 validate-input m-b-16 m-t-26">
                                {{ item }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

shoppingapp/templates/shoppingapp/shoppinglist.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-30 p-r-30 p-t-58">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'chatapp:chatpage' group_pk=group_pk %}" class="txt5">Назад</a></button>
                        <p class="txt3 creategroup-p">Список покупок:</p>
                        <button class="login100-form-btn backbutton-add-participant" type="button"><a href="{% url 'shoppingapp:purchasecreation' group_pk=group_pk %}" class="txt5">Добавить</a></button>
                    </div>
                    {% include 'shoppingapp/includes/inc_shop_ajax.html' %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}