authapp/urls.py
from django.urls import path
from authapp.views import SignInView, SignUpView, SignOutView, VerifyView, UserUpdateView

app_name = 'authapp'
urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('edit/<pk>/', UserUpdateView.as_view(), name='edit'),
    path('verify/', VerifyView.as_view(), name='verify'),
]

chatapp/urls.py
from django.urls import path, include
import chatapp.views as chatapp


app_name = 'shoppingapp'
urlpatterns = [
    path('', chatapp.chatpage, name='chatpage'),
]

family_space/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('groupsapp/', include('groupapp.urls', namespace='groupapp')),
                  path('auth_api/', include('api.apiauthapp.urls')),
                  path('', include('api.apiuserapp.urls')),
                  path('', include('api.apigroupapp.urls')),
                  path('', include('api.apichatapp.urls')),
                  path('', include('api.apitaskapp.urls')),
                  path('', include('api.apieventapp.urls')),
                  path('', include('api.apishopingapp.urls')),
                  path('docs/', include('api.apidocs.urls')),
                  path('auth/', include('authapp.urls', namespace='auth')),
                  path('groupsapp/<group_pk>/shoppingapp/', include('shoppingapp.urls', namespace='shop')),
                  path('groupsapp/<group_pk>/chatapp/', include('chatapp.urls', namespace='chatapp')),
                  path('groupsapp/<group_pk>/tasks/', include('taskapp.urls', namespace='taskapp')),
                  path('groupsapp/<group_pk>/eventsapp/', include('eventapp.urls', namespace='eventapp')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groupapp/urls.py
from django.urls import path, include
import groupapp.views as groupapp


app_name = 'groupapp'
urlpatterns = [

    path('<int:group_pk>/participants/', groupapp.view_one_group, name='view_one_group'), #participants
    path('<int:group_pk>/participants/invite/', groupapp.invite_user, name='invite'),
    path('<int:group_pk>/participants/invite/<friend_pk>/', groupapp.addtogroup, name='addtogroup'),
    path('<int:group_pk>/participants/<friend_pk>/', groupapp.removefromgroup, name='removefromgroup'),
    path('<int:group_pk>/participants/roleedit/<participant_pk>/', groupapp.roleedit, name='roleedit'),
    # path('<user_pk>', groupapp.view_user_groups, name='view_user_groups'),
]

userapp/urls.py
from django.urls import path, include
import userapp.views as userapp
import groupapp.views as groupapp


app_name = 'userapps'
urlpatterns = [

    path('usercontacts/', userapp.view_user_contacts, name='usercontacts'),
    path('addcontact/<friend_pk>', userapp.addcontact, name='addcontact'),
    path('removecontact/<friend_pk>', userapp.removecontact, name='removecontact'),
    path('adduser/<group_pk>', userapp.adduser, name='adduser'),
    path('removeuser/<group_pk>', userapp.removeuser, name='removeuser'),
    path('', groupapp.view_user_groups, name='usergroups'),
    path('creategroup/', userapp.creategroup_page, name='creategroups'),
    path('editgroup/<group_pk>', userapp.editgroup, name='editgroup'),
    path('removegroup/<group_pk>', userapp.removegroup, name='removegroup'),
    path('usersearch/', userapp.usersearch, name='usersearch'),
    path('groupsearch/', userapp.groupsearch, name='groupsearch'),
]

groupapp/models.py
from django.db import models
from enum import Enum

from django.shortcuts import get_object_or_404

from authapp.models import User
from django.contrib.auth.models import AbstractUser



# Create your models here.


class Category(models.Model):
    name = models.CharField(verbose_name='Название категории',
                                     max_length=100,
                                     blank=False,
                                     null=False)
    def __str__(self):
        return self.name


class Group(models.Model):
    title = models.CharField(verbose_name='Название группы',
                             max_length=255,
                             blank=False,
                             null=False)
    description = models.TextField(verbose_name='Описание группы',
                                   blank=True,
                                   null=True)
    is_public = models.BooleanField(verbose_name='Публичная группа',
                                    default=True)
    category = models.ForeignKey(Category,
                                 verbose_name='Категория группы',
                                 on_delete=models.PROTECT)

    def __str__(self):
        return self.title + ' ' + self.category.name

    def get_users(self):
        relations = GroupUser.objects.filter(group=self.pk)
        members = map(lambda item: item.user, relations)

        return members

    def add_user(self, user):
        GroupUser.objects.create(user=user, group=self)
        comment = 'Участник добавлен'
        return comment

    def remove_user(self, user):
        group_user = get_object_or_404(GroupUser, user=user, group=self)
        print('юзер опознан')
        group_user.delete()
        print('и удален из группы')
        comment = 'Участник удален'
        return comment

def get_groups_list(self):
    groups_list = Group.objects.all()
    return groups_list


class RoleChoice(Enum):
    '''
    Задание списка перечесления для поля таблицы через класс
    '''
    ADM = 'Администратор'
    USR = 'Пользователь'

class GroupUser(models.Model):
    '''
    Таблица списка пользователей в группе
    '''
    user = models.ForeignKey(User, verbose_name='Пользователь', related_name='usergroups', on_delete=models.CASCADE)
    role = models.CharField(verbose_name='Роль',
                            max_length=3,
                            choices=[(item.name, item.value) for item in RoleChoice],
                            default=RoleChoice.ADM.name)
    group = models.ForeignKey(Group, related_name='users', on_delete=models.CASCADE)

groupapp/forms.py
from django import forms
from groupapp.models import GroupUser

class RoleEdit(forms.ModelForm):
    class Meta:
            model = GroupUser
            fields = ('role',)

    def __init__(self, *args, **kwargs):
        super(RoleEdit, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'logo-input'
            self.fields[field].label = ""

groupapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from groupapp.forms import RoleEdit
from groupapp.models import Group, get_groups_list, GroupUser
from authapp.models import User
from django.shortcuts import get_object_or_404
# Create your views here.
from userapp.models import UserContactList

@login_required
def view_one_group(request, group_pk):
    '''
    Просмотр участников группы с заданным pk
    '''

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk)
    if not friendlyuser:
        return HttpResponseForbidden()

    members = GroupUser.objects.filter(group=group_pk)
    content = {
        'members': members,
        'group_pk': group_pk
    }

    return render(request, 'groupapp/participants.html', content)

@login_required
def view_user_groups(request):
    '''
    Просмотр списка групп пользователя по его pk
    '''

    relations = GroupUser.objects.filter(user=request.user.pk)
    groups = map(lambda item: item.group, relations)

    content = {
        'groups': groups,
    }

    return render(request, 'groupapp/groupspage.html', content)

@login_required
def invite_user(request, group_pk):
    '''
    Просмотр списка друзей пользователя по его pk, перед добавлением в группу
    '''

    relations = UserContactList.objects.filter(user=request.user.pk)
    contacts = map(lambda item: item.contact_user, relations)
    friendlyusers = GroupUser.objects.filter(group=group_pk)
    ingroup = []
    for i in friendlyusers:
        ingroup.append(i.user)

    content = {
        'contacts': contacts,
        'ingroup': ingroup,
        'group_pk': group_pk
    }

    return render(request, 'groupapp/contactlist.html', content)


@login_required
def addtogroup(request, group_pk, friend_pk):
    '''
    Добавление пользователя из списка друзей в группу
    '''
    my_group = get_object_or_404(Group, pk=group_pk)
    my_friend = get_object_or_404(User, pk=friend_pk)
    GroupUser.objects.create(user=my_friend, group=my_group, role='USR')
    return HttpResponseRedirect(reverse('groupapp:invite', args=[group_pk]))

@login_required
def removefromgroup(request, group_pk, friend_pk):
    '''
    Удаление пользователя из группы залогиненным пользователем
    '''
    my_friend = get_object_or_404(User, pk=friend_pk)
    group_user = get_object_or_404(GroupUser, user=my_friend, group=group_pk)
    group_user.delete()
    return HttpResponseRedirect(reverse('groupapp:view_one_group', args=[group_pk]))

@transaction.atomic
def roleedit(request, group_pk, participant_pk):
    '''
    Редактирование роли участника
    '''

    friendlyuser = GroupUser.objects.filter(group=group_pk, user=request.user.pk, role='ADM')
    if not friendlyuser:
        return HttpResponseForbidden()

    group = get_object_or_404(GroupUser, user=participant_pk, group=group_pk)
    form = RoleEdit(request.POST, instance=group)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groupapp:view_one_group', args=[group_pk]))
    else:
        form = RoleEdit(instance=group)

    content = {
        'edit_form': form,
        'group_pk': group_pk,
        'participant_pk': participant_pk,
    }

    return render(request, 'groupapp/roleedit.html', content)

groupapp/templates/groupapp/contactlist.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-partic-add">
                        <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'groupapp:view_one_group' group_pk=group_pk %}" class="txt5">Назад</a></button>
                        <p class="txt3 creategroup-p">Контакты:</p>
                    </div>
                    {% for item in contacts %}
                        <div class="container-login100-form-btn  m-b-16">
                            <button class="login100-form-btn" id="drop-info" type="button">
                                <a class="txt3" href="#">{{ item.username }}</a>
                            </button>
                            <div class="search-group-drop-info" id="hide-info">
                                <p class="search-group-description">Телефон: {{ item.telephone }}</p>
                                <p class="search-group-description">Почта: {{ item.email }}</p>
                                        {% if item in ingroup %}
                                    <button class="btn-search enroll" type="button">
                                        <a href="#" class="txt7">
                                            В группе
                                        </a>
                                    </button>
                                {% else %}
                                    <button class="btn-search enroll" type="button"><a href="{% url 'groupapp:addtogroup' group_pk=group_pk friend_pk=item.pk %}" class="txt7">Добавить</a></button>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

groupapp/templates/groupapp/groupspage.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form class="login100-form validate-form p-l-40 p-r-40 p-t-78">
                <span class="login100-form-title">FamilySpace</span>
                <div class="container-login100-form m-b-43">
                    <span class="login100-form-main m-b-16">
                        <p class="txt3" id="fordropdownmenu">Мои группы</p>
                        <a href="#" class="txt3" id="drop-menu">Меню</a>
                    </span>

                </div>

                <div class="hide-menu">
                    <ul>
                        <li><a href="{% url 'userapp:creategroups' %}" class="txt3">Создать группу</a></li>
                        <li><a href="{% url 'userapp:groupsearch' %}" class="txt3">Поиск групп</a></li>
                        <li><a href="{% url 'userapp:usercontacts' %}" class="txt3">Мои контакты</a></li>
                        <li><a href="{% url 'userapp:usersearch' %}" class="txt3">Поиск контактов</a></li>
                        <li><a href="{% url 'authapp:edit' user.pk %}" class="txt3">Профиль</a></li>
                        <li><a href="{% url 'authapp:signout' %}" class="txt3">Выйти</a></li>
                    </ul>
                </div>

                {% for group in groups %}
                    <div class="container-login100-form-btn  m-b-16">
                      <button class="login100-form-btn">
                        <a href="{% url 'chatapp:chatpage' group_pk=group.pk %}" class="txt3">{{ group.title }}</a>
                      </button>
                    </div>
                {% endfor %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

groupapp/templates/groupapp/groupspage_old.html
{% extends "userapp/base.html" %}
{% load static %}
{% block body %}

        <div class="flex-container-two" id="shop">

            <div class="flex-block-wrapper-3">
                <div class="btn mainpg">
                        <p id="p-purchase">Ваши группы:</p>
                        <button class="btn-search" id="drop-menu" type="button"><a href="#">Меню</a></button>
                </div>
                <div class="hide-menu">
                    <ul>
                        <li><a href="{% url 'userapp:creategroups' %}">Создать группу</a></li>
                        <li><a href="{% url 'userapp:groupsearch' %}">Поиск групп</a></li>
                        <li><a href="{% url 'userapp:usercontacts' %}">Мои контакты</a></li>
                        <li><a href="{% url 'userapp:usersearch' %}">Поиск контактов</a></li>
                        <li><a href="{% url 'authapp:edit' user.pk %}">Профиль</a></li>
                        <li><a href="{% url 'authapp:signout' %}">Выйти</a></li>
                    </ul>
                </div>

                {% for group in groups %}
                    <div class="btn mainpg">
                        <button class="btn-group" type="button"><a href="{% url 'chatapp:chatpage' group_pk=group.pk %}">{{ group.title }}</a></button>
                    </div>
                {% endfor %}
            </div>
        </div>

{% endblock %}

groupapp/templates/groupapp/participants.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-30 p-r-30 p-t-58">
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <button class="login100-form-btn backbutton-search" type="button"><a href="{% url 'chatapp:chatpage' group_pk=group_pk %}" class="txt5">Назад</a></button>
                        <p class="txt3 creategroup-p">Участники группы:</p>
                        <button class="login100-form-btn backbutton-add-participant" type="button"><a href="{% url 'groupapp:invite' group_pk=group_pk %}" class="txt5">Добавить</a></button>
                    </div>
                    {% for item in members %}
                        <div class="container-login100-form-btn  m-b-16">
                            <div class="participants-button">
                                <div class="role-username txt3">
                                    {{ item.user.username }}
                                </div>
                                <div class="role-change">
                                    <a class="txt7" href="{% url 'groupapp:roleedit' group_pk=group_pk participant_pk=item.user.pk %}">
                                        <span class="sr-nm">{{ item.role }}</span>
                                        <span class="add">Изменить</span>
                                    </a>
                                </div>
                                <div class="role-takeout">
                                    <a class="txt7" href="{% url 'groupapp:removefromgroup' group_pk=group_pk friend_pk=item.user.pk %}">Исключить</a>
                                </div>

                            </div>
                        </div>
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

groupapp/templates/groupapp/roleedit.html
{% extends "userapp/base_new.html" %}
{% load static %}
{% block body %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form p-l-40 p-r-40 p-t-58" action="{% url 'groupapp:roleedit' group_pk=group_pk participant_pk=participant_pk %}" method="post">
                    {% csrf_token %}
                    <span class="login100-form-title">FamilySpace</span>
                    <div class="btn mainpg btn-backbutton-contacts">
                        <button class="login100-form-btn creategroup-btn" type="button"><a href="{% url 'groupapp:view_one_group' group_pk=group_pk %}" class="txt5">Назад</a></button>
                        <p class="txt3 creategroup-p">Изменение роли:</p>
                        <input class="login100-form-btn creategroup-btn" type="submit" value="ОК"/>
                    </div>
                    <div class="container-login100-form-btn  m-b-16">
                        {% for item in edit_form %}
                                {{ item }}
                        {% endfor %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}